FROM quay.io/fedora/fedora-bootc as root

ARG KUBE_MINOR=1.35
RUN dnf install -y \
    kubernetes \
    kubernetes${KUBE_MINOR}-kubeadm \
    cri-o${KUBE_MINOR} \
    openssh-server \
    qemu-guest-agent \
    bind-utils \
    iputils \
    cloud-init \
    dnsmasq \
    && dnf clean all
RUN passwd -d root

RUN sed -i 's|"/opt/cni/bin"|"/var/lib/cni/bin"|g' /etc/crio/crio.conf
