FROM quay.io/fedora/fedora:43

ARG KUBE_MINOR=1.35
RUN dnf install -y -q skopeo kubernetes${KUBE_MINOR}-kubeadm && dnf clean all
RUN echo 'root:100000:65536' > /etc/subuid && \
    echo 'root:100000:65536' > /etc/subgid
