ARG FEDORA_VERSION=43
FROM quay.io/fedora/fedora:${FEDORA_VERSION}

RUN dnf install -y --setopt=install_weak_deps=0 \
	libvirt-client \
	libvirt-daemon \
	libvirt-daemon-driver-qemu \
	libvirt-daemon-driver-storage-core \
	libvirt-daemon-driver-network \
	qemu-kvm \
	virtiofsd \
	passt \
	iputils \
	bind9-next-utils \
	openssh-clients \
	genisoimage \
	podman \
	&& dnf clean all

COPY qemu.conf /etc/libvirt/qemu.conf
COPY libvirtd.conf /etc/libvirt/libvirtd.conf
COPY virtiofsd-wrapper /usr/local/bin/virtiofsd-wrapper
COPY virtiofsd.service /etc/systemd/system/virtiofsd.service

RUN mkdir -p /etc/systemd/system/libvirtd.service.d
COPY libvirtd-override.conf /etc/systemd/system/libvirtd.service.d/override.conf

RUN chmod +x /usr/local/bin/virtiofsd-wrapper
RUN mkdir -p /home/qemu && chown -R qemu:qemu /home/qemu
RUN echo 'root:100000:65536' > /etc/subuid && \
    echo 'root:100000:65536' > /etc/subgid
RUN systemctl enable libvirtd.socket libvirtd-tcp.socket \
    virtlogd.service virtiofsd.service && \
    systemctl mask virtqemud.service virtqemud.socket \
    virtproxyd.service virtproxyd.socket virtproxyd-ro.socket virtproxyd-admin.socket \
    systemd-logind.service getty.target console-getty.service

STOPSIGNAL SIGRTMIN+3
ENTRYPOINT ["/sbin/init"]
